name: Helm Validate - Release Chart
on:
  push:
    branches:
      - main
    paths:
    - 'charts/ngsa/**'
    - '.github/workflows/helm-validate-release.yaml'
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Kube Linter
        id: helm-lint
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              kube-linter lint /workspaces/helm-validate-sample/charts/ngsa
      
      - name: Run Helm Unit Tests
        id: helm-unittest
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              cp -R /workspaces/helm-validate-sample/charts/ngsa /tmp
              helm unittest /tmp/ngsa

      - name: Run Kubeconform Checks
        id: kubeconform-checks
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              helm template /workspaces/helm-validate-sample/charts/ngsa | \
              kubeconform \
              -strict \
              -schema-location default \
              -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
              -

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.HELM_RELEASE_TOKEN }}"
