name: Helm Validate - PR
on:
  pull_request:
    types:
      - opened
      - synchronize
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true
jobs:
  build:
    name: Validate NGSA Helm Chart
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Run Kube Linter
        id: helm-lint
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              kube-linter lint /workspaces/helm-validate-sample/chart/ngsa

      - name: Run Helm Unit Tests
        id: helm-unittest
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              cp -R /workspaces/helm-validate-sample/chart/ngsa /tmp
              helm unittest /tmp/ngsa

      - name: Run Kubeconform Checks
        id: kubeconform-checks
        uses: devcontainers/ci@v0.3
        with:    
          cacheFrom: ghcr.io/joaquinrz/helmv-devcontainer
          push: never
          runCmd: |
              helm template /workspaces/helm-validate-sample/chart/ngsa | \
              kubeconform \
              -strict \
              -schema-location default \
              -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
              -
